[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
fumen = "0.1.2"
itertools = "0.11.0"
rand = "0.8.5"

