[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false

[build]
rustflags = ["-C", "target-feature='+avx2,+avx,+sse2,+avx512f,+avx512bw,+avx512vl'"]

[dependencies]
bitvec = "1.0.1"
tinyvec = "1.8.0"
itertools = "0.13.0"
contracts = "0.6.3"
