[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = { version = "0.8.5", features = ['serde'] }
polynomial = "0.2.4"
itertools = "0.10.5"

tungstenite = "*"
serde = { version = "1.0.78", features = ["derive", "std"] }
serde_json = "1.0.78"
tokio-tungstenite = "*"
tokio = { version = "1.19.2", features = ["full"] }
log = "0.4"
futures-util = { version = "0.3", features = ["sink", "std"] }
url = "2.2.2"
argmin = { version = "0.10", features = ['full', 'serde1', 'rayon'] }
argmin-math = { version = "0.4", features = ["ndarray_latest", "nalgebra_latest"] }
argmin-checkpointing-file = "0.1.0"
argmin-observer-slog = "*"
rand_xoshiro = "*"
rand_distr = "0.4.3"