#![allow(dead_code)]

use crate::bitmatrix::Bitmatrix;
use itertools::chain;
use std::fmt::Display;

pub type COL = u16;
pub const W: usize = 10;
pub const H: usize = COL::BITS as usize;

// Queue Constants
const PIECE_BITS: usize = 3; // 0 is empty piece; 1..7 are Z..T
const MULTIPLIER: usize = 16807;
const MODULUS: usize = 2147483647;

#[derive(Debug, Copy, Clone)]
pub struct Game {
    pub board: Bitmatrix,
    pub queue: u64,
    pub seed: usize,
}

impl Game {
    pub fn new(seed: usize) -> Self {
        let mut out = Self {
            board: Bitmatrix::new(),
            seed,
            queue: 0,
        };
        // set the first 21 pieces
        out.queue = chain!(
            out.shuffle_seven(),
            out.shuffle_seven(),
            out.shuffle_seven()
        )
        .enumerate()
        .fold(0, |q, (i, p)| q | p << (i * PIECE_BITS));

        out
    }

    /// returns the next piece in queue and shifts the queue
    pub fn next(&mut self) -> usize {
        if self.peek_ahead(15) == 0 {
            // 3rd bag is empty
            self.append_next_bag();
        }
        let out = self.peek();
        self.queue >>= PIECE_BITS;
        out
    }

    pub const fn peek(&self) -> usize {
        self.peek_ahead(0)
    }

    /// returns the type of the piece at index n without mutating self
    pub const fn peek_ahead(&self, n: usize) -> usize {
        (self.queue >> (n * PIECE_BITS)) as usize & 0b111
    }

    /// appends to the back of the queue 7 pieces
    /// generated by the tetris random seed
    /// this updates the seed
    fn append_next_bag(&mut self) {
        for (i, piece) in self.shuffle_seven().into_iter().enumerate() {
            self.queue |= piece << ((14 + i) * PIECE_BITS);
        }
    }

    /// creates a shuffled 7-bag (mutates the seed)
    fn shuffle_seven(&mut self) -> [u64; 7] {
        // generates the next bag
        let mut arr = [1, 2, 3, 4, 5, 6, 7];
        for i in (1..7).rev() {
            let r = (self.next_num() * (i as f32 + 1.0)) as usize;
            [arr[i], arr[r]] = [arr[r], arr[i]];
        }
        arr
    }

    /// sets the next seed
    fn next_num(&mut self) -> f32 {
        self.seed = self.seed * MULTIPLIER % MODULUS;
        (self.seed - 1) as f32 / MODULUS as f32
    }
}

impl Display for Game {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.board.fmt(f)
    }
}

const NUM_PIECES: usize = 3;

pub const PIECES: [[[COL; 3]; 4]; NUM_PIECES] = [
    // T
    [
        // N
        [0b100, 0b110, 0b100],
        // E
        [0b000, 0b111, 0b010],
        // S
        [0b010, 0b110, 0b010],
        // W
        [0b010, 0b111, 0b000],
    ],
    // L
    [
        // N
        [0b100, 0b100, 0b110],
        // E
        [0b000, 0b111, 0b100],
        // S
        [0b110, 0b010, 0b010],
        // W
        [0b001, 0b111, 0b000],
    ],
    // O
    [
        // N
        [0b110, 0b110, 0b000],
        // E
        [0b110, 0b110, 0b000],
        // S
        [0b110, 0b110, 0b000],
        // W
        [0b110, 0b110, 0b000],
    ],
];

pub const MASKS: [[[COL; 3]; 4]; NUM_PIECES] = generate_masks();

const fn generate_masks() -> [[[COL; 3]; 4]; NUM_PIECES] {
    let mut masks = PIECES;

    // https://rust-lang.github.io/rfcs/2344-const-looping.html
    let mut piece = 0;
    while piece < NUM_PIECES {
        let mut rot = 0;
        while rot < 4 {
            let mut col = 0;
            while col < 3 {
                let p = PIECES[piece][rot][col];
                masks[piece][rot][col] = (p << 1) + (p << 4) + (p << 7) + (p << 10) + (p << 13);

                col += 1;
            }
            rot += 1;
        }
        piece += 1;
    }

    masks
}

// [+X, +Y] = KICKS[piece][rot][ {CW, CCW} ][test#]
pub const KICKS: [[[[[i32; 2]; 5]; 2]; 4]; 3] = [
    // for T, L, J, S, Z piece:
    // going to N has an implicit -1 offset (so explicitely should be +1)
    // going from N has an implicit +1 offset (explicit -1)
    // all N offsets are 1 lower than in SRS standard

    // T
    [
        // N
        [
            // E
            [[0, -1], [-1, -1], [-1, 0], [0, -3], [-1, -3]],
            // W
            [[0, -1], [1, -1], [1, 0], [0, -3], [1, -3]],
        ],
        // E
        [
            // S
            [[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]],
            // N
            [[0, 1], [1, 1], [1, 0], [0, 3], [1, 3]],
        ],
        // S
        [
            // W
            [[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]],
            // E
            [[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]],
        ],
        // W
        [
            // N
            [[0, 1], [-1, 1], [-1, 0], [0, 3], [-1, 3]],
            // S
            [[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]],
        ],
    ],
    // L
    [
        // N
        [
            // E
            [[0, -1], [-1, -1], [-1, 0], [0, -3], [-1, -3]],
            // W
            [[0, -1], [1, -1], [1, 0], [0, -3], [1, -3]],
        ],
        // E
        [
            // S
            [[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]],
            // N
            [[0, 1], [1, 1], [1, 0], [0, 3], [1, 3]],
        ],
        // S
        [
            // W
            [[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]],
            // E
            [[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]],
        ],
        // W
        [
            // N
            [[0, 1], [-1, 1], [-1, 0], [0, 3], [-1, 3]],
            // S
            [[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]],
        ],
    ],
    // O
    [
        // N
        [
            // E
            [[0, 0], [-1, -1], [-1, 0], [0, -3], [-1, -3]],
            // W
            [[0, 0], [1, -1], [1, 0], [0, -3], [1, -3]],
        ],
        // E
        [
            // S
            [[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]],
            // N
            [[0, 0], [1, 1], [1, 0], [0, 3], [1, 3]],
        ],
        // S
        [
            // W
            [[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]],
            // E
            [[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]],
        ],
        // W
        [
            // N
            [[0, 0], [-1, 1], [-1, 0], [0, 3], [-1, 3]],
            // S
            [[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]],
        ],
    ],
];

// [+X, +Y] = KICKS[piece][rot][test#]
pub const KICKS_180: [[[[i32; 2]; 6]; 4]; 3] = [
    // for T, L, J, S, Z piece:
    // going to N has an implicit -1 offset (so explicitely should be +1)
    // going from N has an implicit +1 offset (explicit -1)
    // all N offsets are 1 lower than in SRS standard

    // T
    [
        // N
        [
            // S
            [0, -1],
            [0, 0],
            [1, 0],
            [-1, 0],
            [1, -1],
            [-1, -1],
        ],
        // E
        [
            // W
            [0, 0],
            [1, 0],
            [1, 2],
            [1, 1],
            [0, 2],
            [0, -1],
        ],
        // S
        [
            // N
            [0, 1],
            [0, 0],
            [-1, 0],
            [1, 0],
            [-1, 1],
            [1, 1],
        ],
        // W
        [
            // E
            [0, 0],
            [-1, 0],
            [-1, 2],
            [-1, 1],
            [0, 2],
            [0, -1],
        ],
    ],
    // L
    [
        // N
        [
            // S
            [0, -1],
            [0, 0],
            [1, 0],
            [-1, 0],
            [1, -1],
            [-1, -1],
        ],
        // E
        [
            // W
            [0, 0],
            [1, 0],
            [1, 2],
            [1, 1],
            [0, 2],
            [0, -1],
        ],
        // S
        [
            // N
            [0, 1],
            [0, 0],
            [-1, 0],
            [1, 0],
            [-1, 1],
            [1, 1],
        ],
        // W
        [
            // E
            [0, 0],
            [-1, 0],
            [-1, 2],
            [-1, 1],
            [0, 2],
            [0, -1],
        ],
    ],
    // O
    [
        // N
        [
            // S
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
        ],
        // E
        [
            // W
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
        ],
        // S
        [
            // N
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
        ],
        // W
        [
            // E
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
            [0, 0],
        ],
    ],
];

#[cfg(test)]
mod piece_queue_tests {
    use super::*;

    #[test]
    fn show_output() {
        // run with -- --show-output
        let mut game = Game::new(4);
        println!("{:#b}", game.queue);
        for _ in 0..15 {
            println!("{:?}", game.next());
        }
    }

    #[test]
    fn test_match_with_osk() {
        let mut game = Game::new(15);
        // ITOSLJZS JOTZLIL
        let osk_queue = [5, 7, 3, 4, 2, 6, 1, 4, 6, 3, 7, 1, 2, 5];

        for piece in osk_queue {
            assert_eq!(game.next(), piece);
        }

        let mut game = Game::new(7000);
        // TSJOLIZITLSJZO
        let osk_queue = [7, 4, 6, 3, 2, 5, 1, 5, 7, 2, 4, 6, 1, 3];
        for piece in osk_queue {
            assert_eq!(game.next(), piece);
        }
    }
}
