#![allow(dead_code)]

use crate::bitmatrix::Bitmatrix;
use itertools::chain;
use std::fmt::Display;

// Queue Constants
const PIECE_BITS: usize = 3; // 0 is empty piece; 1..7 are Z..T
const MULTIPLIER: usize = 16807;
const MODULUS: usize = 2147483647;

#[derive(Debug, Copy, Clone)]
pub struct Game {
    pub board: Bitmatrix,
    pub queue: u64,
    pub hold: u8,
    pub seed: usize,
}

impl Game {
    pub fn new(seed: usize) -> Self {
        let mut out = Self {
            board: Bitmatrix::new(),
            seed,
            hold: 0,
            queue: 0,
        };
        // set the first 21 pieces
        out.queue = chain!(
            out.shuffle_seven(),
            out.shuffle_seven(),
            out.shuffle_seven()
        )
        .enumerate()
        .fold(0, |q, (i, p)| q | p << (i * PIECE_BITS));

        out
    }

    /// returns the next piece in queue and shifts the queue
    pub fn next(&mut self) -> usize {
        if self.peek_ahead(15) == 0 {
            // 3rd bag is empty
            self.append_next_bag();
        }
        let out = self.peek();
        self.queue >>= PIECE_BITS;
        out
    }

    /// if hold is empty, sets hold to the first piece in queue and advances queue
    /// else, swaps hold with the first piece in queue
    /// returns the first piece in queue after holding
    pub fn hold(&mut self) -> usize {
        if self.hold == 0 {
            self.hold = self.next() as u8;
        } else {
            let temp = self.peek() as u8;
            self.queue |= self.hold as u64;
            self.hold = temp;
        }
        return self.peek();
    }
    
    /// returns what hold() would return without mutating self
    pub const fn peek_hold(&self) -> usize {
        if self.hold == 0 {
            return self.peek_ahead(1);
        } else {
            return self.hold as usize;
        }
    }

    pub const fn peek(&self) -> usize {
        self.peek_ahead(0)
    }

    /// returns the type of the piece at index n without mutating self
    pub const fn peek_ahead(&self, n: usize) -> usize {
        (self.queue >> (n * PIECE_BITS)) as usize & ((1 << PIECE_BITS) - 1)
    }

    /// appends to the back of the queue 7 pieces
    /// generated by the tetris random seed
    /// this updates the seed
    fn append_next_bag(&mut self) {
        for (i, piece) in self.shuffle_seven().into_iter().enumerate() {
            self.queue |= piece << ((14 + i) * PIECE_BITS);
        }
    }

    /// creates a shuffled 7-bag (mutates the seed)
    fn shuffle_seven(&mut self) -> [u64; 7] {
        // generates the next bag
        let mut arr = [1, 2, 3, 4, 5, 6, 7];
        for i in (1..7).rev() {
            let r = (self.next_num() * (i as f32 + 1.0)) as usize;
            [arr[i], arr[r]] = [arr[r], arr[i]];
        }
        arr
    }

    /// sets the next seed
    fn next_num(&mut self) -> f32 {
        self.seed = self.seed * MULTIPLIER % MODULUS;
        (self.seed - 1) as f32 / MODULUS as f32
    }
}

impl Display for Game {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.board.fmt(f)
    }
}

#[cfg(test)]
mod piece_queue_tests {
    use super::*;

    #[test]
    fn show_output() {
        // run with -- --show-output
        let mut game = Game::new(4);
        println!("{:#b}", game.queue);
        for _ in 0..15 {
            println!("{:?}", game.next());
        }
    }

    #[test]
    fn test_match_with_osk() {
        let mut game = Game::new(15);
        // ITOSLJZS JOTZLIL
        let osk_queue = [5, 7, 3, 4, 2, 6, 1, 4, 6, 3, 7, 1, 2, 5];

        for piece in osk_queue {
            assert_eq!(game.next(), piece);
        }

        let mut game = Game::new(7000);
        // TSJOLIZITLSJZO
        let osk_queue = [7, 4, 6, 3, 2, 5, 1, 5, 7, 2, 4, 6, 1, 3];
        for piece in osk_queue {
            assert_eq!(game.next(), piece);
        }
    }
}
